# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0cf38034d785897825b379699f26d9376a9a29732fbf139acc2cf1d924d49995c2742f8434ce9bc17f56b40c7e1e4d7484cb39d43966f7513242c4770e83ea42

test:
  secret_key_base: eb07d49bf80829c970ffae27276d57cdce905a335d002cc615bbef95ed78970cd7a354e15b058ef03c251b9d9319d8d19b48470c0102000859d3766c5948aeb5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
